import 'dart:ui';

import 'package:flutter/material.dart';

class AppColors {
  static final Color dark_blue = Color(0xFF3E4653);
  static final Color light_blue = Color(0xFF717f95);
  static final Color light_white = Color(0xfff3f3f4);
  static final Color light_grey = Color(0xffF5F5F5);
  static final Color toggle_color = Color(0xffDDDDDD);
  static final Color pale_white = Color(0xffF7F7F7);
  static final Color white = Colors.white;
  static final Color black = Colors.black;
  static final Color trasparent = Colors.transparent;
  static final Color gold = Colors.amber;
  static final Color grey = Colors.grey;
  static final Color bg_grey = Color(0xffFAFAFA);
  static final Color green = Colors.green;
  static final Color check_green = Color(0xff1DDEA4);
  static final Color cyan = Color(0xff008B8B);
  static final Color red = Colors.red;
  static final Color chilli = Color(0xffFD003A);
  static final Color light_gold = Colors.amber.withOpacity(0.5);
  static final Color splash_blue = Color(0xff325CF0);
  static final Color edit_text_bg = Color(0xffF4F6FA);
  static final Color boader_grey = Color(0xffDCDDEB);
  static final Color divider_grey = Color(0xffDFE6F2);
  static final Color yellow = Color(0xffF3C50F);
  static final Color green_on_board = Color(0xff19D29B);
  static final Color app_light_grey = Color(0xffF5F5F5);
  static final Color grey2 = Color(0xffF2F2F2);
  static final Color grey3 = Color(0xff828282);
  static final Color grey5 = Color(0xffE0E0E0);
  static final Color divider = Color(0xffE1E5EF);
  static final Color app_black = Color(0xff011627);
  static final Color app_yellow = Color(0xffFFB700);
  static final Color app_dark_grey = Color(0xff5A5A5A);
  static final Color app_text_blue = Color(0xff2F80ED);
  static final Color app_light_grey_2 = Color(0xff7C7C7C);
  static final Color app_light_grey_3 = Color(0xffA4A4A4);
  static final Color app_light_grey_4 = Color(0xffC4C4C4);
  static final Color app_light_grey_5 = Color(0xffdedede);
  static final Color app_white_bg = Color(0xffE5E5E5).withOpacity(0.1);
  static final Color app_pink = Color(0xffF30F53);
  static final Color app_dark_blue = Color(0xff300FFA);
  static final Color app_orange = Color(0xffFF9E0D);
  static final Color app_light_blue = Color(0xff08A1F7);
  static final Color app_light_red = Color(0xffFA6464);
  static final Color app_light_red_group = Color(0xffF45151);
  static final Color app_light_blue_group = Color(0xff51CCF4);
  static final Color app_light_green = Color(0xff10C08B);
  static final Color app_light_yellow = Color(0xffF9E2AA);
  static final Color app_border = Color(0xffF1F1F1);
}
